version: 2

project_name: master

before:
  hooks:
    - rm -rf ./dist
    - go mod tidy
    - git push
    - git push --tags
builds:
  - id: master
    main: ./bin/master
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: master
  - id: master_slu
    main: ./bin/master_slu
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: master_slu
  - id: master_slr
    main: ./bin/master_slr
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: master_slr
  - id: master_tergum
    main: ./bin/master_tergum
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: master_tergum

archives:
  - formats: [ "tar.gz" ]
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - master
      - master_slu
      - master_slr
      - master_tergum

release:
  prerelease: auto

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

brews:
  -
    name: master
    repository:
      owner: sikalabsx
      name: homebrew-tap
    skip_upload: auto
    homepage: https://github.com/sikalabsx/master
    url_template: "https://github.com/sikalabsx/master/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    directory: Formula
    caveats: "How to use this binary: https://github.com/sikalabsx/master"
    description: "master"
    install: |
      bin.install "master"
      bin.install "master_slu"
      bin.install "master_slr"
      bin.install "master_tergum"
    test: |
      system "#{bin}/master version"

dockers:
    -
      goos: linux
      goarch: amd64
      image_templates:
        - "ghcr.io/sikalabsx/master:{{ .Tag }}"
      dockerfile: Dockerfile.goreleaser
      ids:
        - master
        - master_slu
        - master_slr
        - master_tergum
      build_flag_templates:
        - "--platform=linux/amd64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/sikalabsx/master"
        - "--label=maintainer=Ondrej Sika &lt;ondrej@sika.io&gt;"
    - goos: linux
      goarch: arm64
      image_templates:
        - "ghcr.io/sikalabsx/master:{{ .Tag }}-arm64v8"
      dockerfile: Dockerfile.goreleaser.arm64v8
      ids:
        - master
        - master_slu
        - master_slr
        - master_tergum
      build_flag_templates:
        - "--platform=linux/arm64"
        - "--label=org.opencontainers.image.created={{.Date}}"
        - "--label=org.opencontainers.image.title={{.ProjectName}}"
        - "--label=org.opencontainers.image.revision={{.FullCommit}}"
        - "--label=org.opencontainers.image.version={{.Version}}"
        - "--label=org.label-schema.schema-version=1.0"
        - "--label=org.label-schema.version={{.Version}}"
        - "--label=org.label-schema.name={{.ProjectName}}"
        - "--label=com.github.actions.name={{.ProjectName}}"
        - "--label=repository=https://github.com/sikalabsx/master"
        - "--label=maintainer=Ondrej Sika &lt;ondrej@sika.io&gt;"
